const SubscriptionActionTypes ={
    FETCH_CREATE_SUBSCRIPTION_START:'FETCH_CREATE_SUBSCRIPTION_START',
    FETCH_CREATE_SUBSCRIPTION_FAILURE:'FETCH_CREATE_SUBSCRIPTION_FAILURE'
}

export default SubscriptionActionTypes;
