const FetchingActionTypes = {
    IS_FETCHING:"IS_FETCHING",
    IS_FETCHING_FORM:"IS_FETCHING_FORM",
    FETCHING_SUCCESS:"FETCHING_SUCCESS",
    FETCHING_COMPLETE: "FETCHING_COMPLETE"
}

export default FetchingActionTypes;
