const ProductActionTypes ={
    FETCH_GET_CATEGORY_START:'FETCH_GET_CATEGORY_START',
    FETCH_GET_CATEGORY_SUCCESS:'FETCH_GET_CATEGORY_SUCCESS',
    FETCH_GET_CATEGORY_FAILURE:'FETCH_GET_CATEGORY_FAILURE',
    SET_CATEGORY_FILTER:'SET_CATEGORY_FILTER',
}

export default ProductActionTypes;
